### ISSUE TITLE
Black boxes -> Caixas-pretas

### ISSUE THREAD

**Issue by bledson** [tsouanas/fmcbook#1]
É comum na literatura da computação (em português) o uso do termo 'caixa-preta' para descrever, por exemplo, um programa que não conhecemos os detalhes de implementação. A sugestão é então evitar o termo em inglês.

**Comment by tsouanas** [comment]
Oi Bledson, obrigado pelo teu feedback!  Fico sabendo da existencia desse termo em pt, mas por enquanto optei para usar mais o ingles.  Em geral, no pt-Θ, tem certas influencias fortes de outras linguas, ingles uma delas, e nesse caso nao tenho decidido ainda qual dos termos vou usar mais, mas com certeza quero pelo menos mencionar os dois!  Eu percebi depois da tua mensagem que nem tinha aparecido o "caixa-preta" mesmo na sua primeira introducao (no capitulo de conjuntos)!  Obrigado, eu acabei de adicionar o termo.  Algo parecido acontece depois nos reticulados, onde fico usando as vezes o ingles "lattice" mesmo que o "reticulado" eh um termo bem estabelecido em pt.  Uma outra coisa que mudei bastante foi o "coset" que usava antigamente no fmcbook para o "coclasse" que eh o termo usado em pt...
