### ISSUE TITLE
Maior diferenciação entre tópicos

### ISSUE THREAD

**Issue by bledson** [tsouanas/fmcbook#11]
Assim como exemplos recebem títulos em negrito e em fonte menor, precedidos de um ponto preto, sugiro diferentes estilos para os outros elementos:

* Unir pares de perguntas e respostas: o que consegui pensar é que sejam as perguntas precedidas por uma checkbox vazia e a resposta por uma checkbox marcada;
* Observações: não consigo pensar numa sugestão aqui, mas algo que sirva para indicar que é uma observação "filha" de um tópico precedente;

**Comment by tsouanas** [comment]
Boa(s) idéia(s)!  Mas tem uns probleminhos.
[Note que isso é um "issue" do thatex e não do fmcbook.]                                                                                                                                       
                                                                                                                                                                                               
Internalmente (no ThaTeX), existe o \question, então o próprio ThaTeX sabe que isso é uma questão.  Inicialmente eu tinha criado (junto com o \question) um \answer para respostas também, mas acabei retirando.  Inclusive, umas respostas são dadas como \note (que aparece como "Item com numeração") e outras como \blah (que aparece sem numeração).  Ambos (\note e \blah) quando uso para dar resposta, em geral aparecem com um titulozinho, que na maioria das vezes é a palavra "Resposta", mas isso não é um built-in.  Pode ser que apareça "Quase-resposta" em alguma questão, ou "resposta errada", por exemplo.

Quando eu tinha definido \question & \answer, eu tava pensando em usos onde o \answer aparece bem depois duma questão, e tinha criado um linkinho entre os dois, mas acabei não usando na prá(c)tica.  E retirei.  E confesso que depois botei de volta, e depois re-retirei.

...E agora depois da tua mensagem tó repensando sobre re-botar o \answer                                                                                                                       
de novo ehehehhe.

(Um probleminho é que pode ter \answer sem \question, pois talvez perguntou a questão dentro de uma coisa sem separá-la como \question.  Então não pode forçar esse link entre \question<-\answer.)

Sobre as observações (\remark) acho tranquilo no jeito que tá, e note que não são "filhas" de algum "parent-paragraph" em geral.

**Comment by bledson** [comment]
Entendi a questão. O problema surgiu quando eu me deparei gastando um certo tempo precisando ler o que vem após a numeração para achar alguma parte específica (questão/resposta, definição etc.), e com essa separação visual já filtraria alguns itens.

**Comment by tsouanas** [comment]
Hmmm entendi.  Mas tem que "botar uma linha" pois depois se tem muitos simbolizinhos diferenciados um para cada uma das possibilidades, vai acabar atrapalhando mesmo...  (E no PDF pode aproveitar a busca do teu leitor e os hyperlinks tambem...)

**Comment by tsouanas** [comment]
Creio que com as novas funcionalidades e mudanças no ThaTeX, esse ponto foi (finalmente) bem atendido.
Agora tenho um \of para referir em outros itens relacionados.

Por exemplo:

\answer.
\of question_label_here

\proof.
\of theorem_label_here

Valeu!
