### ISSUE TITLE
Problema na dica x15.8

### ISSUE THREAD

**Issue by tyronedamasceno** [tsouanas/fmcbook#15]
No exercício x15.8 é definida a relação:

`R(x, y) ⇐def⇒ a pessoa x leu a palavra y num livro` e pergunta se essa é igual à relação `Author ⋄ Read` que chamarei de S.

Porém Author e Read nem são relações componíveis.

Além disso, na dica 1 dessa questão, tem-se as intensões das relações.
R = _a pessoa x leu a palavra y num livro_
S = _a pessoa x leu um livro onde a palavra y aparece_

E claramente esta não é a intensão da S.

**Comment by tyronedamasceno** [comment]
Acredito que a ideia seria usar `S = Read ⋄ Contains`

**Comment by tsouanas** [comment]
Foi sim!  Corrigido; obrigado!
