### ISSUE TITLE
"Formulamente" -> "Formalmente" pág 162, versão 20180831230503

### ISSUE THREAD

**Issue by bledson** [tsouanas/fmcbook#6]

**Comment by tsouanas** [comment]
Isso foi de proposito..
Em pt-Θ:
formalmente = numa maneira formal
formulamente = com formulas

**Comment by vcvpaiva** [comment]
Desculpe mas formulamente nao existe. Existe formulaico q talvez de pra fazer formulaicamente.

**Comment by tsouanas** [comment]
Não existe... onde?  No fmcbook, existe :P
Reminder: o idioma do fmcbook é português de Θάνος

Obs: o "formulaico" não serve aqui---mas obrigado pois não sabia dessa palavra! :D
